# Virtual Agora Configuration File v1.3
# Node-centric architecture with specialized agent tools

# The Moderator is a specialized reasoning tool for process facilitation.
# A powerful model is recommended for complex analytical tasks.
moderator:
  provider: google
  model: gemini-2.5-flash-lite

# The Summarizer compresses round discussions into compacted context.
# Consistent summarization quality is important for context flow.
summarizer:
  provider: google
  model: gemini-2.5-flash-lite

# The Topic Report Agent synthesizes concluded agenda items.
# Strong analytical capabilities required for comprehensive reporting.
topic_report:
  provider: google
  model: gemini-2.5-flash-lite

# The Ecclesia Report Agent creates the final session analysis.
# Premium model recommended for sophisticated cross-topic synthesis.
ecclesia_report:
  provider: google
  model: gemini-2.5-flash-lite

# The list of agents that will participate in the discussion.
# These are the primary debate participants.
agents:
  - provider: google
    model: gemini-2.5-flash-lite
    count: 3
