# Virtual Agora Configuration File v1.3
# Copy this file to the root directory as config.yml and customize as needed

# The Moderator is a specialized reasoning tool for process facilitation.
# A powerful model is recommended for complex analytical tasks.
moderator:
  provider: Google
  model: gemini-2.5-pro

# The Summarizer compresses round discussions into compacted context.
# Consistent summarization quality is important for context flow.
summarizer:
  provider: OpenAI
  model: gpt-4o

# The Topic Report Agent synthesizes concluded agenda items.
# Strong analytical capabilities required for comprehensive reporting.
topic_report:
  provider: Anthropic
  model: claude-3-opus-20240229

# The Ecclesia Report Agent creates the final session analysis.
# Premium model recommended for sophisticated cross-topic synthesis.
ecclesia_report:
  provider: Google
  model: gemini-2.5-pro

# The list of agents that will participate in the discussion.
# These are the primary debate participants.
agents:
  # OpenAI agents
  - provider: OpenAI
    model: gpt-4o
    count: 2  # Creates gpt-4o-1 and gpt-4o-2

  # Anthropic agent
  - provider: Anthropic
    model: claude-3-opus-20240229
    count: 1

  # Google agent
  - provider: Google
    model: gemini-2.5-pro
    count: 1

  # Grok agent (uncomment and specify model when available)
  # - provider: Grok
  #   model: <grok_model_name>
  #   count: 1
